# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import donation_pb2 as donation__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in donation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DonationServiceStub(object):
    """Сервис для генерации ссылок на оплату и проверки статуса транзакции
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePaymentLink = channel.unary_unary(
                '/donation.DonationService/CreatePaymentLink',
                request_serializer=donation__pb2.CreatePaymentRequest.SerializeToString,
                response_deserializer=donation__pb2.CreatePaymentResponse.FromString,
                _registered_method=True)
        self.CheckTransactionStatus = channel.unary_unary(
                '/donation.DonationService/CheckTransactionStatus',
                request_serializer=donation__pb2.CheckTransactionStatusRequest.SerializeToString,
                response_deserializer=donation__pb2.CheckTransactionStatusResponse.FromString,
                _registered_method=True)
        self.GetPaymentQRCode = channel.unary_unary(
                '/donation.DonationService/GetPaymentQRCode',
                request_serializer=donation__pb2.GetQRCodeRequest.SerializeToString,
                response_deserializer=donation__pb2.GetQRCodeResponse.FromString,
                _registered_method=True)
        self.UpdateDonationStatus = channel.unary_unary(
                '/donation.DonationService/UpdateDonationStatus',
                request_serializer=donation__pb2.UpdateDonationStatusRequest.SerializeToString,
                response_deserializer=donation__pb2.UpdateDonationStatusResponse.FromString,
                _registered_method=True)


class DonationServiceServicer(object):
    """Сервис для генерации ссылок на оплату и проверки статуса транзакции
    """

    def CreatePaymentLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckTransactionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentQRCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDonationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DonationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePaymentLink': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePaymentLink,
                    request_deserializer=donation__pb2.CreatePaymentRequest.FromString,
                    response_serializer=donation__pb2.CreatePaymentResponse.SerializeToString,
            ),
            'CheckTransactionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTransactionStatus,
                    request_deserializer=donation__pb2.CheckTransactionStatusRequest.FromString,
                    response_serializer=donation__pb2.CheckTransactionStatusResponse.SerializeToString,
            ),
            'GetPaymentQRCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentQRCode,
                    request_deserializer=donation__pb2.GetQRCodeRequest.FromString,
                    response_serializer=donation__pb2.GetQRCodeResponse.SerializeToString,
            ),
            'UpdateDonationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDonationStatus,
                    request_deserializer=donation__pb2.UpdateDonationStatusRequest.FromString,
                    response_serializer=donation__pb2.UpdateDonationStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'donation.DonationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('donation.DonationService', rpc_method_handlers)


class DonationService(object):
    """Сервис для генерации ссылок на оплату и проверки статуса транзакции
    """

    @staticmethod
    def CreatePaymentLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donation.DonationService/CreatePaymentLink',
            donation__pb2.CreatePaymentRequest.SerializeToString,
            donation__pb2.CreatePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckTransactionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donation.DonationService/CheckTransactionStatus',
            donation__pb2.CheckTransactionStatusRequest.SerializeToString,
            donation__pb2.CheckTransactionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaymentQRCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donation.DonationService/GetPaymentQRCode',
            donation__pb2.GetQRCodeRequest.SerializeToString,
            donation__pb2.GetQRCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDonationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donation.DonationService/UpdateDonationStatus',
            donation__pb2.UpdateDonationStatusRequest.SerializeToString,
            donation__pb2.UpdateDonationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
