"""Add assets table and update donations

Revision ID: 2ab95ea51998
Revises: 001
Create Date: 2025-05-30 08:07:33.886687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab95ea51998'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('network', sa.VARCHAR(length=20), nullable=False),
    sa.Column('contract_address', sa.VARCHAR(length=42), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_network'), 'assets', ['network'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.add_column('donations', sa.Column('asset_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_donations_asset_id'), 'donations', ['asset_id'], unique=False)
    op.create_foreign_key(None, 'donations', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.drop_column('donations', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.drop_index(op.f('ix_donations_asset_id'), table_name='donations')
    op.drop_column('donations', 'asset_id')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index(op.f('ix_assets_network'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
